### ISSUE TITLE
When creating a new site (vinterrutt) => error with addOwnedSite

### ISSUE THREAD

**Issue by mathieuLU** [biodiversitydata-se/biocollect#191]
After fixing the issue #177 (https://github.com/biodiversitydata-se/biocollect/issues/177), another minor issue popped up :+1: 

it seems that the routine to add the Owner for the site does not work : 

ecodata side :
```
2022-01-06 15:38:50.656 ERROR --- [-apr-443-exec-1] o.s.b.w.servlet.support.ErrorPageFilter  : Forwarding to error page from request [/ws/person/addOwnedSite/35af2711-e759-4da9-b0f4-bdd615790289] due to exception [Could not resolve view with name 'addOwnedSite' in servlet with name 'grailsDispatcherServlet']

javax.servlet.ServletException: Could not resolve view with name 'addOwnedSite' in servlet with name 'grailsDispatcherServlet'
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1352)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1118)

```

biocollect side :
```

java.io.IOException: Server returned HTTP response code: 500 for URL: https://ecodata.biodiversitydata.se/ws/person/addOwnedSite/35af2711-e759-4da9-b0f4-bdd615790289
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1897)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1495)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)

```

**Comment by mathieuLU** [comment]
fixed with commit on ecodata https://github.com/biodiversitydata-se/ecodata/commit/804ea82e4b6b9e6d65a816924fd58971f7715bf6

only 2 lines of code in the end, but 2 hours to debug it :D
