### ISSUE TITLE
email service not configured

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/biocollect#28]
error issues during updating survey form but shows whenever a notification should be issued 

2020-09-14 15:09:47,585 ERROR [MailMessageBuilder]  Failed to send email
org.springframework.mail.MailSendException: Mail server connection failed; nested exception is com.sun.mail.util.MailConnectException: Couldn't connect to host, port: act-ironport-int.csiro.au, 25; timeout -1;
  nested exception is:
	java.net.ConnectException: Connection timed out (Connection timed out). Failed messages: com.sun.mail.util.MailConnectException: Couldn't connect to host, port: act-ironport-int.csiro.au, 25; timeout -1;
  nested exception is:
	java.net.ConnectException: Connection timed out (Connection timed out); message exception details (1) are:
Failed message 1:
com.sun.mail.util.MailConnectException: Couldn't connect to host, port: act-ironport-int.csiro.au, 25; timeout -1;
  nested exception is:
	java.net.ConnectException: Connection timed out (Connection timed out)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1984)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:656)
	at javax.mail.Service.connect(Service.java:345)
	at grails.plugin.mail.MailMessageBuilder$_sendMessage_closure1.doCall(MailMessageBuilder.groovy:125)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at java.net.Socket.connect(Socket.java:556)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:301)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:229)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:1950)
	... 6 more

**Comment by mathieuLU** [comment]
yes we should try to play with the config file

grails.mail.host=act-ironport-int.csiro.au
grails.mail.port=25
emailFilter=/[A-Z0-9._%-]+@csiro\.au|chris\.godwin\.ala@gmail.com|christophergodwin@yahoo.com.au/
biocollect.support.email.address = biocollect-support@ala.org.au
biocollect.system.email.replyTo = biocollect-dev<no-reply>@ala.org.au
biocollect.system.email.sender = biocollect-(dev)@ala.org.au

I changed it to :
grails.mail.host=smtps.lu.se              
grails.mail.port=587
biocollect.support.email.address = mathieu.blanchet@biol.lu.se 
biocollect.system.email.replyTo = mathieu.blanchet@biol.lu.se        
biocollect.system.email.sender = mathieu.blanchet@biol.lu.se 

No chance that it could work haha
I don't understand the role of the emailFilter

**Comment by magdziarek** [comment]
ERROR --- [ool-23-thread-2] grails.plugins.mail.MailMessageBuilder   : Failed to send email

org.springframework.mail.MailSendException: Mail server connection failed; nested exception is com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtps.lu.se              , 587; timeout -1;
  nested exception is: java.net.UnknownHostException: smtps.lu.se

**Comment by magdziarek** [comment]
ERROR --- [ool-23-thread-2] grails.plugins.mail.MailMessageBuilder   : Failed to send email

org.springframework.mail.MailSendException: Mail server connection failed; nested exception is com.sun.mail.util.MailConnectException: Couldn't connect to host, port: smtps.lu.se              , 587; timeout -1;
  nested exception is: java.net.UnknownHostException: smtps.lu.se
