### ISSUE TITLE
hub config - cannot save images

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/biocollect#38]
Cannot save images for banner or footer.

Console error: POST https://biocollect.bioatlas.se/lusm/admin/saveHubSettings 500

Ecodata: 
[http-nio-80-exec-265] ERROR errors.GrailsExceptionResolver  - IllegalStateException occurred when processing request: [POST] /ws/document
Illegal access: this web application instance has been stopped already. Could not load [javax.imageio.IIOParam]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.. Stacktrace follows:
java.lang.IllegalStateException: Illegal access: this web application instance has been stopped already. Could not load [javax.imageio.IIOParam]. The following stack trace is thrown for debugging purposes as well as to attempt to terminate the thread which caused the illegal access.

BioColllect:
[apr-443-exec-70] o.g.web.errors.GrailsExceptionResolver   : NullPointerException occurred when processing request: [POST] /lusm/admin/saveHubSettings
Cannot get property 'documentId' on null object. Stacktrace follows:

java.lang.NullPointerException: Cannot get property 'documentId' on null object
	at au.org.ala.biocollect.merit.AdminController$_saveHubSettings_closure5.doCall(AdminController.groovy:452)
	at au.org.ala.biocollect.merit.AdminController.saveHubSettings(AdminController.groovy:442)
	at org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker.invoke(DefaultGrailsControllerClass.java:223)
	at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:188)
	at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:54)
	at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
	at au.org.ala.cas.client.AlaHttpServletRequestWrapperFilter.doFilter(AlaHttpServletRequestWrapperFilter.java:81)
	at org.jasig.cas.client.validation.AbstractTicketValidationFilter.doFilter(AbstractTicketValidationFilter.java:236)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:188)
	at org.jasig.cas.client.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:155)
	at au.org.ala.cas.client.UriFilter.doFilter(UriFilter.java:188)
	at org.jasig.cas.client.session.SingleSignOutFilter.doFilter(SingleSignOutFilter.java:97)
	at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:128)
	at org.springframework.boot.web.support.ErrorPageFilter.access$000(ErrorPageFilter.java:66)
	at org.springframework.boot.web.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:103)
	at org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:121)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by magdziarek** [comment]
- make sure the image is a png
- change permissions recursively on /data/ecodata/uploads folder
- restart ecodata and biocollect (because of the thread with illegal access error above)
- same applies for images for projects saved in BioCollect
- when an image is saved it should be saved in data/ecodata/uploads and should be referenced in "documents" collection in ecodata
