### ISSUE TITLE
SUNET instance crashed - monitor behaviour

### ISSUE THREAD

**Issue by magdziarek** [biodiversitydata-se/biocollect#71]
This time BioCollect itself, it happened with Ecodata twice before. Ecodata was fine this time, just BC crashed, no access to tomcat manager either, restarting it from command line works

**Comment by magdziarek** [comment]
crashed again

**Comment by magdziarek** [comment]
crashed again. Terminal output:
First:
020-11-11 09:05:52.328 DEBUG --- [pr-443-exec-121] a.o.ala.biocollect.merit.SearchService   : url = http://ecodata.bioatlas.se/ws/search/elasticProjectActivity?hub=lusm&max=10000&view=project&projectId=1fb10915-e6c0-451e-b575-b7e715d5d32f&userIsAlaAdmin=true&userIsProjectAdmin=true&userCanEditProject=true&userId=6&offset=0&flimit=20&sort=lastUpdated&order=DESC&fq=&searchTerm=
[[name:Sjofagel, images:null], [name:Punktlokal, images:null], [name:Nattrutt, images:null], [name:Vinterrutt, images:null], [name:Standardrutt, images:null], [name:Kustfagelrutor, images:null], [name:Slinga, images:null], [name:Sommarrutt, images:null]]
free(): corrupted unsorted chunks

Then no activity and then:
11-Nov-2020 09:58:58.803 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/common/classes], exists: [false], isDirectory: [false], canRead: [false]
11-Nov-2020 09:58:58.805 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/common], exists: [false], isDirectory: [false], canRead: [false]
11-Nov-2020 09:58:59.137 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.39 (Ubuntu)
11-Nov-2020 09:58:59.137 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 9 2019 19:47:51 UTC
11-Nov-2020 09:58:59.137 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.39.0
11-Nov-2020 09:58:59.137 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
11-Nov-2020 09:58:59.137 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.15.0-45-generic
11-Nov-2020 09:58:59.137 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
11-Nov-2020 09:58:59.137 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
11-Nov-2020 09:58:59.138 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_272-8u272-b10-0ubuntu1~18.04-b10
11-Nov-2020 09:58:59.138 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Private Build
11-Nov-2020 09:58:59.138 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /var/lib/tomcat8
11-Nov-2020 09:58:59.138 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/share/tomcat8
11-Nov-2020 09:58:59.138 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/var/lib/tomcat8/conf/logging.properties
11-Nov-2020 09:58:59.138 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
11-Nov-2020 09:58:59.138 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
11-Nov-2020 09:58:59.138 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseConcMarkSweepGC
11-Nov-2020 09:58:59.138 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
11-Nov-2020 09:58:59.138 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
11-Nov-2020 09:58:59.138 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
11-Nov-2020 09:58:59.138 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
11-Nov-2020 09:58:59.138 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/var/lib/tomcat8
11-Nov-2020 09:58:59.139 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/share/tomcat8
11-Nov-2020 09:58:59.139 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/tmp/tomcat8-tomcat8-tmp
11-Nov-2020 09:58:59.139 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.21] using APR version [1.6.3].
11-Nov-2020 09:58:59.139 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
11-Nov-2020 09:58:59.139 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
11-Nov-2020 09:58:59.141 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.1  11 Sep 2018]
11-Nov-2020 09:58:59.210 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-80"]
11-Nov-2020 09:58:59.221 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
11-Nov-2020 09:58:59.231 INFO [main] org.apache.coyote.http11.AbstractHttp11Protocol.configureUpgradeProtocol The ["https-openssl-apr-443"] connector has been configured to support negotiation to [h2] via ALPN
11-Nov-2020 09:58:59.231 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["https-openssl-apr-443"]
11-Nov-2020 09:58:59.293 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 454 ms
11-Nov-2020 09:58:59.307 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
11-Nov-2020 09:58:59.307 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.39 (Ubuntu)
11-Nov-2020 09:58:59.314 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying configuration descriptor [/etc/tomcat8/Catalina/localhost/manager.xml]
11-Nov-2020 09:58:59.943 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
11-Nov-2020 09:58:59.970 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deployment of configuration descriptor [/etc/tomcat8/Catalina/localhost/manager.xml] has finished in [656] ms
11-Nov-2020 09:58:59.971 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying configuration descriptor [/etc/tomcat8/Catalina/localhost/host-manager.xml]
11-Nov-2020 09:59:00.227 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
11-Nov-2020 09:59:00.231 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deployment of configuration descriptor [/etc/tomcat8/Catalina/localhost/host-manager.xml] has finished in [260] ms

**Comment by magdziarek** [comment]
crashed again
while it crashed the manager/html was not accessible but tomcat said it was active:

ubuntu@biocollect:~$ service tomcat8 status 
● tomcat8.service - LSB: Start Tomcat.
   Loaded: loaded (/etc/init.d/tomcat8; generated)
   Active: active (exited) since Wed 2020-12-09 15:05:15 UTC; 23h ago
     Docs: man:systemd-sysv-generator(8)

Dec 09 15:05:10 biocollect systemd[1]: Starting LSB: Start Tomcat....
Dec 09 15:05:10 biocollect tomcat8[21479]:  * Starting Tomcat servlet engine tom
Dec 09 15:05:15 biocollect tomcat8[21479]:    ...done.
Dec 09 15:05:15 biocollect systemd[1]: Started LSB: Start Tomcat..

**Comment by magdziarek** [comment]
14-Dec-2020 11:23:05.782 INFO [http-nio-80-exec-10] org.apache.catalina.core.ApplicationContext.log HTMLManager: list: Listing contexts for virtual host 'localhost'
14-Dec-2020 11:23:08.137 INFO [http-nio-80-exec-8] org.apache.catalina.core.ApplicationContext.log HTMLManager: undeploy: Undeploying web application at '/'
14-Dec-2020 11:23:08.140 INFO [http-nio-80-exec-8] org.apache.catalina.core.ApplicationContext.log Destroying Spring FrameworkServlet 'grailsDispatcherServlet'
14-Dec-2020 11:23:08.174 INFO [http-nio-80-exec-8] org.apache.catalina.core.ApplicationContext.log Closing Spring root WebApplicationContext
14-Dec-2020 11:23:09.252 INFO [http-nio-80-exec-8] org.apache.catalina.core.ApplicationContext.log HTMLManager: list: Listing contexts for virtual host 'localhost'
14-Dec-2020 11:23:22.397 INFO [http-nio-80-exec-10] org.apache.catalina.core.ApplicationContext.log HTMLManager: list: Listing contexts for virtual host 'localhost'
14-Dec-2020 11:23:24.344 INFO [http-nio-80-exec-7] org.apache.catalina.core.ApplicationContext.log HTMLManager: list: Listing contexts for virtual host 'localhost'
14-Dec-2020 11:23:33.377 INFO [localhost-startStop-2] org.apache.catalina.core.ApplicationContext.log 2 Spring WebApplicationInitializers detected on classpath
14-Dec-2020 11:23:38.286 INFO [localhost-startStop-2] org.apache.catalina.core.ApplicationContext.log Initializing Spring embedded WebApplicationContext
14-Dec-2020 11:23:42.687 INFO [localhost-startStop-2] org.apache.catalina.core.ApplicationContext.log Initializing Spring FrameworkServlet 'grailsDispatcherServlet'
14-Dec-2020 11:23:48.032 INFO [http-nio-80-exec-3] org.apache.catalina.core.ApplicationContext.log HTMLManager: list: Listing contexts for virtual host 'localhost'
14-Dec-2020 11:31:06.432 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log 2 Spring WebApplicationInitializers detected on classpath
14-Dec-2020 11:31:12.379 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log Initializing Spring embedded WebApplicationContext
14-Dec-2020 11:31:17.612 INFO [localhost-startStop-1] org.apache.catalina.core.ApplicationContext.log Initializing Spring FrameworkServlet 'grailsDispatcherServlet'

**Comment by mathieuLU** [comment]
it's crazy how we can't see anything in the logs. Today for instance. Nothing done on the instance durinng the mornin. I launch several requests at the same time (displaying the data tab ob standardrutterna + 2 tabs with details of a route)
=> crash (page can't be reached)

The crash is at 9:13. The restart at 9:14 (server time is one hour less, so 8:13)

Logs : 
12-Jan-2021 01:01:46.292 INFO [https-openssl-apr-443-exec-29] org.apache.coyote.http11.Http11Processor.service Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:479)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:684)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2127)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

12-Jan-2021 08:14:17.442 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/common/classes], exists: [false], isDirectory: [false], canRead: [false]
12-Jan-2021 08:14:17.444 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/common], exists: [false], isDirectory: [false], canRead: [false]
12-Jan-2021 08:14:17.445 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/common/classes], exists: [false], isDirectory: [false], canRead: [false]
12-Jan-2021 08:14:17.445 WARNING [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/common], exists: [false], isDirectory: [false], canRead: [false]
12-Jan-2021 08:14:17.446 WARNIN

the lines starting with "WARNING [main] org.apache.catalina.startup.ClassLoader" are always displayed once you have launched the restart of tomcat. So they come in the process of the restart, and not before the crash :)

a file is created in /var/crash, but can't do anything with it. Nothing as well in other logs

**Comment by mathieuLU** [comment]
It happened again this morning. Same way : I open biocollect, get connected, and then try to open several tab at the same time. This morning I tried to open "Nattrutt" and "Standardrutt" at the same time (2 different tabs) from the menu "Läs om de olika delprogrammen"

crashed at 8:45, reboot at 8:48. Nothing in the logs.

I'll try to dig into the logs from apport:

ubuntu@biocollect:/var/log$ cat apport.log
ERROR: apport (pid 26480) Wed Jan 13 07:45:15 2021: called for pid 18240, signal 6, core limit 0, dump mode 1
ERROR: apport (pid 26480) Wed Jan 13 07:45:15 2021: executable: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java (command line "/usr/lib/jvm/java-8-openjdk-amd64/bin/java -Djava.util.logging.config.file=/var/lib/tomcat8/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.awt.headless=true -XX:+UseConcMarkSweepGC -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Dorg.apache.catalina.security.SecurityListener.UMASK=0027 -Dignore.endorsed.dirs= -classpath /usr/share/tomcat8/bin/bootstrap.jar:/usr/share/tomcat8/bin/tomcat-juli.jar -Dcatalina.base=/var/lib/tomcat8 -Dcatalina.home=/usr/share/tomcat8 -Djava.io.tmpdir=/tmp/tomcat8-tomcat8-tmp org.apache.catalina.startup.Bootstrap start")
ERROR: apport (pid 26480) Wed Jan 13 07:45:15 2021: is_closing_session(): no DBUS_SESSION_BUS_ADDRESS in environment
ERROR: apport (pid 26480) Wed Jan 13 07:47:06 2021: wrote report /var/crash/_usr_lib_jvm_java-8-openjdk-amd64_jre_bin_java.111.crash
